name = "viroshort"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

# Node.js compatibility for your dependencies
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "viroshort"
# Environment variables for production
[env.production.vars]
NODE_ENV = "production"

[env.preview]
name = "viroshort-preview"
# Environment variables for preview
[env.preview.vars]
NODE_ENV = "preview"

[[env.production.bindings]]
name = "DB"
type = "d1"

[[env.preview.bindings]]
name = "DB" 
type = "d1" 